"""maintenance at classroom and exam model

Revision ID: 0cff7221a8b8
Revises: c6e519e511e2
Create Date: 2025-04-24 04:02:38.731462

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0cff7221a8b8'
down_revision = 'c6e519e511e2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_classroom', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classroom_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('student_classroom_ibfk_4', type_='foreignkey')
        batch_op.drop_constraint('student_classroom_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(None, 'classroom', ['classroom_id'], ['id'])
        batch_op.drop_column('fk_student_classroom_classroom_id')
        batch_op.drop_column('exam_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_classroom', schema=None) as batch_op:
        batch_op.add_column(sa.Column('exam_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('fk_student_classroom_classroom_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('student_classroom_ibfk_3', 'exams', ['exam_id'], ['id'])
        batch_op.create_foreign_key('student_classroom_ibfk_4', 'classroom', ['fk_student_classroom_classroom_id'], ['id'])
        batch_op.drop_column('classroom_id')

    # ### end Alembic commands ###
