"""Add response_payload to QuestionGenerated

Revision ID: 0e480f38316b
Revises: 3d57e8897d3a
Create Date: 2025-08-23 13:27:09.238435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e480f38316b'
down_revision = '3d57e8897d3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_generated', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_payload', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_generated', schema=None) as batch_op:
        batch_op.drop_column('response_payload')

    # ### end Alembic commands ###
