"""added created_at on classroom models

Revision ID: 1399faa5e18b
Revises: 626dd0bf49d8
Create Date: 2025-10-09 08:18:26.950003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1399faa5e18b'
down_revision = '626dd0bf49d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classroom', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classroom', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
