"""fix recreate database

Revision ID: 1b24da8658cc
Revises: afb746adcf20
Create Date: 2025-08-08 04:13:39.258782

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1b24da8658cc'
down_revision = 'afb746adcf20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('score', sa.Float(), nullable=True))
        batch_op.drop_constraint('exam_attempts_ibfk_1', type_='foreignkey')
        batch_op.drop_column('created_at')
        batch_op.drop_column('classroom_id')
        batch_op.drop_column('answers')
        batch_op.drop_column('external_response')

    with op.batch_alter_table('exam_questions', schema=None) as batch_op:
        batch_op.drop_constraint('exam_questions_ibfk_2', type_='foreignkey')
        batch_op.drop_column('question_id')
        batch_op.drop_column('question_metadata')

    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('end_time', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('duration',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.drop_index('uuid')
        batch_op.drop_constraint('exams_ibfk_2', type_='foreignkey')
        batch_op.drop_constraint('exams_ibfk_3', type_='foreignkey')
        batch_op.drop_constraint('exams_ibfk_1', type_='foreignkey')
        batch_op.drop_column('title_exam')
        batch_op.drop_column('deadline')
        batch_op.drop_column('attempt_limit')
        batch_op.drop_column('difficulty')
        batch_op.drop_column('question_type')
        batch_op.drop_column('questions_number')
        batch_op.drop_column('uuid')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uuid', mysql.VARCHAR(length=36), nullable=False))
        batch_op.add_column(sa.Column('questions_number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('question_type', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('difficulty', mysql.VARCHAR(length=10), nullable=False))
        batch_op.add_column(sa.Column('attempt_limit', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('deadline', mysql.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('title_exam', mysql.VARCHAR(length=100), nullable=False))
        batch_op.create_foreign_key('exams_ibfk_1', 'classroom', ['classroom_id'], ['id'])
        batch_op.create_foreign_key('exams_ibfk_3', 'modules', ['module_id'], ['id'])
        batch_op.create_foreign_key('exams_ibfk_2', 'users', ['created_by'], ['id'])
        batch_op.create_index('uuid', ['uuid'], unique=True)
        batch_op.alter_column('duration',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('end_time')
        batch_op.drop_column('start_time')
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    with op.batch_alter_table('exam_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_metadata', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
        batch_op.add_column(sa.Column('question_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('exam_questions_ibfk_2', 'exams', ['question_id'], ['id'])

    with op.batch_alter_table('exam_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_response', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
        batch_op.add_column(sa.Column('answers', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=False))
        batch_op.add_column(sa.Column('classroom_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.create_foreign_key('exam_attempts_ibfk_1', 'classroom', ['classroom_id'], ['id'])
        batch_op.drop_column('score')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('started_at')

    # ### end Alembic commands ###
