"""refactor Modules

Revision ID: 2c17f48cf02d
Revises: cc1334165d31
Create Date: 2025-11-20 11:25:58.032776

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2c17f48cf02d'
down_revision = 'cc1334165d31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('module_name', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('file_url', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('uploaded_by', sa.Integer(), nullable=False))
        batch_op.drop_constraint('modules_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['uploaded_by'], ['id'])
        batch_op.drop_column('classroom_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classroom_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('modules_ibfk_1', 'classroom', ['classroom_id'], ['id'])
        batch_op.drop_column('uploaded_by')
        batch_op.drop_column('file_url')
        batch_op.drop_column('module_name')

    # ### end Alembic commands ###
