"""update on QuestionGenerated

Revision ID: 336cf7f336dd
Revises: 6b48f36bf491
Create Date: 2025-07-30 14:17:05.077402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '336cf7f336dd'
down_revision = '6b48f36bf491'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_generated', schema=None) as batch_op:
        batch_op.add_column(sa.Column('module_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_generated', schema=None) as batch_op:
        batch_op.drop_column('user_id')
        batch_op.drop_column('module_id')

    # ### end Alembic commands ###
