"""update ExamQuestion Models

Revision ID: 3d57e8897d3a
Revises: e67080dc7b0c
Create Date: 2025-08-20 10:16:29.945863

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3d57e8897d3a'
down_revision = 'e67080dc7b0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_metadata', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('question_data', sa.JSON(), nullable=True))
        batch_op.create_index(batch_op.f('ix_exam_questions_exam_id'), ['exam_id'], unique=False)
        batch_op.drop_column('question_text')
        batch_op.drop_column('options')
        batch_op.drop_column('correct_answer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correct_answer', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('options', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=False))
        batch_op.add_column(sa.Column('question_text', mysql.TEXT(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_exam_questions_exam_id'))
        batch_op.drop_column('question_data')
        batch_op.drop_column('question_metadata')

    # ### end Alembic commands ###
