"""refactor modules

Revision ID: 423af4d3ee60
Revises: 2c17f48cf02d
Create Date: 2025-11-23 11:14:59.787734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '423af4d3ee60'
down_revision = '2c17f48cf02d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resource_name', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('job_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('classroom_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'classroom', ['classroom_id'], ['id'])
        batch_op.drop_column('resource_id')
        batch_op.drop_column('file_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_url', mysql.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('resource_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('classroom_id')
        batch_op.drop_column('job_id')
        batch_op.drop_column('resource_name')

    # ### end Alembic commands ###
