"""Update ExamAnswer models

Revision ID: 4dd79c599059
Revises: df49cdcf6dd8
Create Date: 2025-08-25 13:00:30.910704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4dd79c599059'
down_revision = 'df49cdcf6dd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_answers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint('uq_attempt_question', ['attempt_id', 'question_id'])

    with op.batch_alter_table('exam_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answers', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_attempts', schema=None) as batch_op:
        batch_op.drop_column('answers')

    with op.batch_alter_table('exam_answers', schema=None) as batch_op:
        batch_op.drop_constraint('uq_attempt_question', type_='unique')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
