"""add classroomId on ExamQuestion and GeneratedQuestion

Revision ID: 5011be734ed0
Revises: 423af4d3ee60
Create Date: 2025-11-23 14:58:55.050475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5011be734ed0'
down_revision = '423af4d3ee60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classroom_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_exam_questions_classroom_id'), ['classroom_id'], unique=False)

    with op.batch_alter_table('question_generated', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classroom_id', sa.Integer(), nullable=False))
        batch_op.create_index(batch_op.f('ix_question_generated_classroom_id'), ['classroom_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_generated', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_question_generated_classroom_id'))
        batch_op.drop_column('classroom_id')

    with op.batch_alter_table('exam_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_questions_classroom_id'))
        batch_op.drop_column('classroom_id')

    # ### end Alembic commands ###
