"""add update_at column in QuestionGenerated

Revision ID: 5a3ca56e8adf
Revises: f7f1f907112a
Create Date: 2025-09-19 01:58:58.540748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a3ca56e8adf'
down_revision = 'f7f1f907112a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_generated', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_generated', schema=None) as batch_op:
        batch_op.drop_column('update_at')

    # ### end Alembic commands ###
