"""add new models and routes

Revision ID: 5fdc987715bc
Revises: 0cff7221a8b8
Create Date: 2025-04-24 14:41:45.317210

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5fdc987715bc'
down_revision = '0cff7221a8b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tittle_exam', sa.String(length=100), nullable=False))
        batch_op.drop_constraint('exams_ibfk_1', type_='foreignkey')
        batch_op.drop_constraint('exams_ibfk_2', type_='foreignkey')
        batch_op.drop_column('question_id')
        batch_op.drop_column('answer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('answer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('question_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('exams_ibfk_2', 'question_exams', ['question_id'], ['id'])
        batch_op.create_foreign_key('exams_ibfk_1', 'answer_exams', ['answer_id'], ['id'])
        batch_op.drop_column('tittle_exam')

    # ### end Alembic commands ###
