"""Update Exam models

Revision ID: 60023af45bce
Revises: 8a7e8eb65be7
Create Date: 2025-08-25 11:42:17.014182

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '60023af45bce'
down_revision = '8a7e8eb65be7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_index('job_id')
        batch_op.drop_column('level')
        batch_op.drop_column('job_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', mysql.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('level', mysql.VARCHAR(length=10), nullable=False))
        batch_op.create_index('job_id', ['job_id'], unique=True)

    # ### end Alembic commands ###
