"""update length on QuestionGeneratedResult

Revision ID: 6b48f36bf491
Revises: 7efd43ebd5a5
Create Date: 2025-07-20 15:54:42.082100

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b48f36bf491'
down_revision = '7efd43ebd5a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_generated_result', schema=None) as batch_op:
        batch_op.alter_column('job_id',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_generated_result', schema=None) as batch_op:
        batch_op.alter_column('job_id',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
