"""refactor at ExamAttempt

Revision ID: 6ec5029e7454
Revises: 83581e01270a
Create Date: 2025-10-05 09:44:44.475973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ec5029e7454'
down_revision = '83581e01270a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attempt_number', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('external_response', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_attempts', schema=None) as batch_op:
        batch_op.drop_column('external_response')
        batch_op.drop_column('status')
        batch_op.drop_column('attempt_number')

    # ### end Alembic commands ###
