"""delete a few row at QuestionGeneratedResult

Revision ID: 788f15f0e0bb
Revises: c2348aa000f1
Create Date: 2025-08-11 15:06:54.043104

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '788f15f0e0bb'
down_revision = 'c2348aa000f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_generated_result', schema=None) as batch_op:
        batch_op.drop_column('insert_message')
        batch_op.drop_column('result_message')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_generated_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('result_message', mysql.TEXT(), nullable=False))
        batch_op.add_column(sa.Column('insert_message', mysql.TEXT(), nullable=False))

    # ### end Alembic commands ###
