"""fix update_at to updated_at on QuestionGenerated Models

Revision ID: 83581e01270a
Revises: bb11e0b143df
Create Date: 2025-09-24 08:17:49.153558

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '83581e01270a'
down_revision = 'bb11e0b143df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_generated', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('update_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_generated', schema=None) as batch_op:
        batch_op.add_column(sa.Column('update_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
