"""Add response_payload to QuestionGenerated

Revision ID: 8a7e8eb65be7
Revises: 0e480f38316b
Create Date: 2025-08-23 14:02:14.749831

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8a7e8eb65be7'
down_revision = '0e480f38316b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_generated', schema=None) as batch_op:
        batch_op.alter_column('response_payload',
               existing_type=mysql.DATETIME(),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_generated', schema=None) as batch_op:
        batch_op.alter_column('response_payload',
               existing_type=sa.JSON(),
               type_=mysql.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
