"""add module_id, level, quiz_type on QuestionGeneratedResult

Revision ID: 8c8b7feafd4d
Revises: 9ba35b1c2304
Create Date: 2025-08-08 20:33:03.051627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c8b7feafd4d'
down_revision = '9ba35b1c2304'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_id', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('level', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('quiz_type', sa.String(length=50), nullable=False))
        batch_op.create_unique_constraint(None, ['job_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exams', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('quiz_type')
        batch_op.drop_column('level')
        batch_op.drop_column('job_id')

    # ### end Alembic commands ###
