"""add module_id, level, quiz_type on QuestionGeneratedResult

Revision ID: 9ba35b1c2304
Revises: 1b24da8658cc
Create Date: 2025-08-08 18:56:46.169697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ba35b1c2304'
down_revision = '1b24da8658cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_answer', sa.String(length=255), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['exam_attempts.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['exam_questions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('question_generated_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('module_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('level', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('quiz_type', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_generated_result', schema=None) as batch_op:
        batch_op.drop_column('quiz_type')
        batch_op.drop_column('level')
        batch_op.drop_column('module_id')

    op.drop_table('exam_answers')
    # ### end Alembic commands ###
