"""delete a few row at QuestionGeneratedResult

Revision ID: 9eacbe12e190
Revises: 788f15f0e0bb
Create Date: 2025-08-11 15:11:01.013095

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9eacbe12e190'
down_revision = '788f15f0e0bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_generated_result', schema=None) as batch_op:
        batch_op.drop_column('started_at')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('enqueued_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_generated_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enqueued_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('started_at', mysql.DATETIME(), nullable=True))

    # ### end Alembic commands ###
