"""Recreate migration

Revision ID: b04c030d9967
Revises: 
Create Date: 2025-04-10 17:25:39.844973

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b04c030d9967'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_classroom', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_student_classroom_classroom_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'classroom', ['fk_student_classroom_classroom_id'], ['id'])
        batch_op.drop_column('clasroom_id')
        batch_op.drop_column('classroom_id')

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'users', ['teacher_id'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('first_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('last_name', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('access_code', sa.String(length=50), nullable=True))
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_column('access_code')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('student_classroom', schema=None) as batch_op:
        batch_op.add_column(sa.Column('classroom_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('clasroom_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fk_student_classroom_classroom_id')

    # ### end Alembic commands ###
