"""add generate_id, module_id, quiz_type, difficulty on ExamQuestion

Revision ID: bb11e0b143df
Revises: 5a3ca56e8adf
Create Date: 2025-09-19 22:59:06.516212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb11e0b143df'
down_revision = '5a3ca56e8adf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_questions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generated_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('module_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quiz_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('difficulty', sa.String(length=50), nullable=True))
        batch_op.create_index('idx_exam_module', ['exam_id', 'module_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_questions_generated_id'), ['generated_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_questions_module_id'), ['module_id'], unique=False)
        batch_op.create_foreign_key(None, 'question_generated', ['generated_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_questions', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_exam_questions_module_id'))
        batch_op.drop_index(batch_op.f('ix_exam_questions_generated_id'))
        batch_op.drop_index('idx_exam_module')
        batch_op.drop_column('difficulty')
        batch_op.drop_column('quiz_type')
        batch_op.drop_column('module_id')
        batch_op.drop_column('generated_id')

    # ### end Alembic commands ###
