"""add module_id, level, quiz_type on QuestionGeneratedResult

Revision ID: c2348aa000f1
Revises: 8c8b7feafd4d
Create Date: 2025-08-09 01:14:59.815247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2348aa000f1'
down_revision = '8c8b7feafd4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_generated_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_id', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('question_generated_result', schema=None) as batch_op:
        batch_op.drop_column('question_id')

    # ### end Alembic commands ###
