"""added new table, classroom_module

Revision ID: cc1334165d31
Revises: d0f80058ff67
Create Date: 2025-11-20 10:30:33.186463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc1334165d31'
down_revision = 'd0f80058ff67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classroom_modules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['classroom_id'], ['classroom.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('classroom_modules')
    # ### end Alembic commands ###
