"""Update ExamAttempt models

Revision ID: df49cdcf6dd8
Revises: 60023af45bce
Create Date: 2025-08-25 11:45:20.251704

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df49cdcf6dd8'
down_revision = '60023af45bce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submitted_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('completed_at')
        batch_op.drop_column('started_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('started_at', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', mysql.DATETIME(), nullable=True))
        batch_op.drop_column('submitted_at')

    # ### end Alembic commands ###
