"""empty message

Revision ID: e0a24ac4d88e
Revises: c9cda629142b
Create Date: 2025-03-02 05:04:22.515993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0a24ac4d88e'
down_revision = 'c9cda629142b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_date', sa.Date(), nullable=False))
        batch_op.drop_column('birth_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birth_name', sa.DATE(), nullable=False))
        batch_op.drop_column('birth_date')

    # ### end Alembic commands ###
