"""Update exam_id to True values on ExamQuestion Models

Revision ID: f7f1f907112a
Revises: 4dd79c599059
Create Date: 2025-09-16 02:36:20.823649

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7f1f907112a'
down_revision = '4dd79c599059'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_questions', schema=None) as batch_op:
        batch_op.alter_column('exam_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('exam_questions', schema=None) as batch_op:
        batch_op.alter_column('exam_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
